server:
  port: 8080

spring:
  profiles:
    active: dev
#person:
#    age: 18
#    boss: false
#    bitrh: 2020/10/17
#    map: {k1: v1,k2: v2}
#    list:
#      - lisi
#      - wangwu
#      - zhangsi
#    dog:
#      name: haby
#      age: 2
#    name: 张三
---
server:
  port: 8083
spring:
  profiles: dev

---
server:
  port: 8082
spring:
  profiles: prod